project:
  type: website

website:
  title: "Los Yarumos de Medellín"
  navbar:
    left:
      - text: Inicio
        href: index.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: false



